platform :ios, '6.0'

target :'UAFilterableResultsController', :exclusive => true do
        pod 'ReactiveCocoa'
end

target :'UAFilterableResultsControllerTests', :exclusive => true do
        pod 'Kiwi/XCTest'
end
